version: '3.8'

services:
  web:
    build: .
    image: seo-tool:latest    # Add this line to name your image
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/seotool
    env_file:
      - app/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: